site_name: Learning DevOps
site_description: A collection of DevOps tools and technologies
site_author: Rojan Adhikari
site_url: https://docs.rojanadhikari.dev
markdown_extensions:
  - attr_list
theme: 
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.expand
    - navigation.path
    - content.code.copy
    - toc.follow
    - navigation.indexes
    # - toc.integrate
    # - navigation.top

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
 
nav: 
  - Jenkins: 
    - Jenkins: jenkins.md
    - Jenkins-Docker: jenkins-docker.md
    - Jenkins-Docker-K8s: jenkins-docker-k8s.md
    - Jenkins-Buildtools: jenkins-buildtools.md
    - Jenkins-master-slave: jenkins-master-slave.md
  - Docker:
    - Docker: docker.md
    - Docker-compose: docker-compose.md
    - Jenkins-Docker: jenkins-docker.md
  
  - EKS: eks.md
  - Sonarqube: sonarqube.md
  - Nexus: nexus.md
  - ELK stack: elk-stack.md
  - Devops: devops.md
  - Jenkins-Docker-K8s: jenkins-docker-k8s.md
  - Ansible: ansible.md
  - MySQLDb: mysql.md
  - MiniKube: minikube.md
  - Terraform: terraform.md
  - Terraform1: terraform1.md


extra:
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/rojan998/
      name: Linkedin
    - icon: fontawesome/solid/paper-plane
      link: mailto:<adhikari.rojan619@gmail.com>
      name: Email
    - icon: fontawesome/solid/r
      link: https://rojanadhikari.dev/
      name: Website
copyright: Copyright &copy; 2025 Rojan Adhikari
